name: C++ Tests

on:
  push:
    branches: [ main, master, sec ]
  pull_request:
    branches: [ main, master, sec ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install -y build-essential libgtest-dev libgmock-dev
        
    - name: Install Google Test
      run: |
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        sudo ldconfig
        
    - name: Build and run tests
      run: |
        cd tests
        g++ -std=c++17 -Wall test_example.cpp -I/usr/local/include -L/usr/local/lib -lgtest -lgtest_main -pthread -o test_runner
        ./test_runner