name: C++ Tests

on:
  push:
    branches: [ main, master, sec ]
  pull_request:
    branches: [ main, master, sec ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Create build directory
      run: mkdir build
        
    - name: Configure CMake
      run: |
        cd build
        cmake ..
        
    - name: Build project
      run: |
        cd build
        make
        
    - name: Run tests
      run: |
        cd build
        ctest --verbose
        
    - name: Run main application
      run: |
        cd build
        ./jetpath